Towards NODECURE_ASYNC_HOOKS compatibility
Revise TimeoutWatchdog's state variables.
- Introduce the notion of a "timer epoch"
  An epoch begins when we start a fresh timer for this call stack
- Introduce various helper APIs (_StartEpoch, _SignalWatchdog)
  for encapsulation and to centralize logging for these operations
- Clarify the use of the Leash/Unleash member variables
- Fix "race" in TimeoutWatchdog::Async

About 30 tests fail when we turn on async-hooks.

Many of these tests fail when TimeoutWatchdog::AfterHook() is called
when there is no stack.
It's unclear to me how this can happen,
since it implies that TimeoutWatchdog::BeforeHook() was not called.

If this is the case, it's probably due to the "experimental" state of async-hooks.
Note for example that 12 of these failures happen in tests for the "domain" module,
which is deprecated.

It may be, then, that the failing tests are due to bad interactions between
deprecated and experimental modules.

Configuration:
$ env | grep NODECURE
NODECURE_THREADPOOL_TIMEOUT_MS=9999999999
NODECURE_NODE_TIMEOUT_MS=999999999
NODECURE_ASYNC_HOOKS=1

Failing tests:
$ make -j4 test 2>&1 | grep Command
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/async-hooks/test-embedder.api.async-resource.after-on-destroyed.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/async-hooks/test-embedder.api.async-resource.improper-order.js
Command: out/Release/node --expose-internals /home/jamie/Desktop/ehp-attacks/node-cure/test/async-hooks/test-no-assert-when-disabled.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-cluster-uncaught-exception.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-common.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-crypto-domain.js
AssertionError [ERR_ASSERTION]: Test index 0 failed: Error: Command failed: ulimit -c 0 && "/home/jamie/Desktop/ehp-attacks/node-cure/out/Release/node" --abort-on-uncaught-exception "/home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-domain-abort-on-uncaught.js" child 0
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-domain-abort-on-uncaught.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-domain-error-types.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-domain-multiple-errors.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-domain-nested.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-domain-nexttick.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-domain-stack.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-domain-stack-empty-in-process-uncaughtexception.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-domain-timers.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-domain-top-level-error-handler-clears-stack.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-emit-after-uncaught-exception.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-domain-with-abort-on-uncaught-exception.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-exception-handler2.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-fs-copyfile.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-fs-fsync.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-handle-wrap-close-abort.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-http2-respond-file-push.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-next-tick-errors.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-process-next-tick.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-repl-eval-scope.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-repl-null-thrown.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-repl-save-load.js
Command: out/Release/node --preserve-symlinks /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-require-symlink.js
Error: Command failed: /home/jamie/Desktop/ehp-attacks/node-cure/out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/fixtures/uncaught-exceptions/callbackify2.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-util-callbackify.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-vm-timeout.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-zlib-from-gzip-with-trailing-garbage.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/parallel/test-zlib-truncated.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/async-hooks/test-embedder.api.async-resource.improper-order.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/async-hooks/test-embedder.api.async-resource.after-on-destroyed.js
Command: out/Release/node --expose-internals /home/jamie/Desktop/ehp-attacks/node-cure/test/async-hooks/test-no-assert-when-disabled.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/addons/callback-scope/test.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/addons/make-callback-recurse/test.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/addons/hello-world-esm/test.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/addons/async-hooks-promise/test.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/addons/async-hello-world/test-makecallback-uncaught.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/addons-napi/test_make_callback_recurse/test.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/sequential/test-inspector-async-hook-teardown-at-debug-end.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/sequential/test-next-tick-error-spin.js
Command: out/Release/node /home/jamie/Desktop/ehp-attacks/node-cure/test/pseudo-tty/test-tty-stdout-end.js